#ifndef __MEALY_CONFIG_H
#define __MEALY_CONFIG_H

#include "morphy_config.h"

#ifdef LIBMEALY_SHARED
#	define MEALY_API MORPHY_EXPORT
#else
#	define MEALY_API MORPHY_IMPORT
#endif

#define MEALY_CALLCONV MORPHY_CALLCONV

#define MEALY_VERSION_MAJOR MORPHY_VERSION_MAJOR
#define MEALY_VERSION_MINOR MORPHY_VERSION_MINOR
#define MEALY_VERSION_PATCH MORPHY_VERSION_PATCH
#define MEALY_VERSION MORPHY_VERSION

#define MEALY_ERROR_MAX_LENGTH 4096

#endif // __MEALY_CONFIG_H
